### ISSUE TITLE
What should I do with font file references in the css file?

### ISSUE THREAD

**Issue by yansenlei** [catdad/css-raw-loader#5]
What should I do with `font file` references in the css file?

```css
@font-face {
  font-family: 'element-icons';
  src: url("fonts/element-icons.woff") format("woff"), url("fonts/element-icons.ttf") format("truetype");
  /* chrome, firefox, opera, Safari, Android, iOS 4.2+*/
  font-weight: normal;
  font-style: normal;
}
```
